# Generated by Django 4.1.2 on 2022-11-03 10:43

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_txt_edit_alter_homepage_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('txt_block', wagtail.blocks.RichTextBlock())], blank=True, use_json_field=None),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='txt_edit',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Описание сайта'),
        ),
    ]
