# Generated by Django 4.1.2 on 2022-11-03 11:30

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('txt_block', wagtail.blocks.RichTextBlock())], use_json_field=True),
        ),
    ]
