# Generated by Django 4.1.2 on 2022-11-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Components', models.CharField(max_length=100, verbose_name='Компоненты')),
                ('Component_description', models.TextField(max_length=1000, verbose_name='Описание')),
            ],
        ),
    ]
