# Generated by Django 4.1.2 on 2022-11-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_components_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='category',
        ),
    ]
