# Generated by Django 4.1.2 on 2022-11-04 11:13

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_components_body_alter_components_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='body',
        ),
        migrations.AddField(
            model_name='components',
            name='fullname',
            field=models.TextField(max_length=1000, null=True, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='components',
            name='description',
            field=wagtail.fields.StreamField([('txt_block', wagtail.blocks.RichTextBlock())], blank=True, null=True, use_json_field=True, verbose_name='Описание изделия'),
        ),
    ]
