# Generated by Django 4.1.2 on 2022-11-04 11:50

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_components_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='description',
            field=wagtail.fields.StreamField([('insert', wagtail.blocks.RichTextBlock())], blank=True, null=True, use_json_field=True, verbose_name='Описание изделия'),
        ),
    ]
