# Generated by Django 4.1.2 on 2022-11-04 12:54

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_components_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='description',
            field=wagtail.fields.StreamField([('insert', wagtail.blocks.RichTextBlock(features=['image', 'h2', 'ul', 'link', 'bold', 'code'], label='Вставить блок'))], blank=True, help_text='Напишите об изделии все, что считаете необходимым', null=True, use_json_field=True, verbose_name='Описание изделия'),
        ),
    ]
