# Generated by Django 4.1.3 on 2022-11-14 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_productpage_categories_productpage_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name_category', to='products.productcategory'),
        ),
    ]
