# Generated by Django 4.1.2 on 2022-11-04 17:07

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_components_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='description',
            field=wagtail.fields.StreamField([('insert_text', wagtail.blocks.RichTextBlock(features=['h2', 'ul', 'link', 'bold', 'code'], label='Вставить текст')), ('insert_image', wagtail.images.blocks.ImageChooserBlock(label='Вставить изображение'))], blank=True, help_text='Напишите об изделии все, что считаете необходимым', null=True, use_json_field=True, verbose_name='Описание изделия'),
        ),
    ]
