# Generated by Django 4.1.3 on 2022-11-14 08:32

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productpage_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryEditing',
            fields=[
                ('productcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.productcategory')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_category', to='products.productpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('products.productcategory', models.Model),
        ),
    ]
