# Generated by Django 4.1.3 on 2022-11-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productcategoryediting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategoryEditing',
        ),
    ]
